/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;


public class App {
    
    public static void main(String[] args) throws SQLException {
                
       /* //Usar o BD
        Connection c = ConnectionFactory.getConnection();
        //Fechar a conexão com o BD
        ConnectionFactory.closeConnection(c);*/
        
       /* ProjectController projectController = new ProjectController();
       
       Project project = new Project();
       project.setName("Project TESTE 2");
       project.setDescription("Description");
       projectController.save(project);*/
        
        
       /*ProjectController projectController = new ProjectController();
       
       Project project = new Project();
       project.setId(1);
       project.setName("Renomear Project TESTE");
       project.setDescription("Description");
       projectController.update(project);
       
       List<Project> projects = projectController.getAll();
       System.out.println("\nTotal de projetos: " + projects.size());
       
       projectController.removeById(1);*/
       
       
      // TaskController taskController = new TaskController();
       
       //Task task = new Task();
      /* task.setIdProject(2);
       task.setName("Tarefa teste 2");
       
       task.setName("Nome tarefa teste");
       task.setDescription("Descrição teste");
       task.setNotes("notas");
       task.setIsCompleted(Boolean.FALSE);
       task.setDeadline(new Date());
       
       
       // taskController.save(task);
       
       
       task.setName("NOME TAREFA ALTERADO");
       //task.setId(1);
       task.setId(1);
       //taskController.update(task);
       
       List<Task> tasks = taskController.getAll(2);
       System.out.println("\nTotal de projetos: " + tasks.size());*/
       
     //  taskController.removeById(3);
       
       
       
       
       
       
       
       
       
       
        
        
    }
}
